/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface RfDisplayHotel {
    }
    interface RfFacilities {
    }
    interface RfHotel {
    }
    interface RfNavbar {
    }
    interface RfPhoto {
    }
    interface RfProperty {
    }
    interface RfRooms {
    }
}
declare global {
    interface HTMLRfDisplayHotelElement extends Components.RfDisplayHotel, HTMLStencilElement {
    }
    var HTMLRfDisplayHotelElement: {
        prototype: HTMLRfDisplayHotelElement;
        new (): HTMLRfDisplayHotelElement;
    };
    interface HTMLRfFacilitiesElement extends Components.RfFacilities, HTMLStencilElement {
    }
    var HTMLRfFacilitiesElement: {
        prototype: HTMLRfFacilitiesElement;
        new (): HTMLRfFacilitiesElement;
    };
    interface HTMLRfHotelElement extends Components.RfHotel, HTMLStencilElement {
    }
    var HTMLRfHotelElement: {
        prototype: HTMLRfHotelElement;
        new (): HTMLRfHotelElement;
    };
    interface HTMLRfNavbarElement extends Components.RfNavbar, HTMLStencilElement {
    }
    var HTMLRfNavbarElement: {
        prototype: HTMLRfNavbarElement;
        new (): HTMLRfNavbarElement;
    };
    interface HTMLRfPhotoElement extends Components.RfPhoto, HTMLStencilElement {
    }
    var HTMLRfPhotoElement: {
        prototype: HTMLRfPhotoElement;
        new (): HTMLRfPhotoElement;
    };
    interface HTMLRfPropertyElement extends Components.RfProperty, HTMLStencilElement {
    }
    var HTMLRfPropertyElement: {
        prototype: HTMLRfPropertyElement;
        new (): HTMLRfPropertyElement;
    };
    interface HTMLRfRoomsElement extends Components.RfRooms, HTMLStencilElement {
    }
    var HTMLRfRoomsElement: {
        prototype: HTMLRfRoomsElement;
        new (): HTMLRfRoomsElement;
    };
    interface HTMLElementTagNameMap {
        "rf-display-hotel": HTMLRfDisplayHotelElement;
        "rf-facilities": HTMLRfFacilitiesElement;
        "rf-hotel": HTMLRfHotelElement;
        "rf-navbar": HTMLRfNavbarElement;
        "rf-photo": HTMLRfPhotoElement;
        "rf-property": HTMLRfPropertyElement;
        "rf-rooms": HTMLRfRoomsElement;
    }
}
declare namespace LocalJSX {
    interface RfDisplayHotel {
    }
    interface RfFacilities {
    }
    interface RfHotel {
    }
    interface RfNavbar {
    }
    interface RfPhoto {
    }
    interface RfProperty {
    }
    interface RfRooms {
    }
    interface IntrinsicElements {
        "rf-display-hotel": RfDisplayHotel;
        "rf-facilities": RfFacilities;
        "rf-hotel": RfHotel;
        "rf-navbar": RfNavbar;
        "rf-photo": RfPhoto;
        "rf-property": RfProperty;
        "rf-rooms": RfRooms;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-display-hotel": LocalJSX.RfDisplayHotel & JSXBase.HTMLAttributes<HTMLRfDisplayHotelElement>;
            "rf-facilities": LocalJSX.RfFacilities & JSXBase.HTMLAttributes<HTMLRfFacilitiesElement>;
            "rf-hotel": LocalJSX.RfHotel & JSXBase.HTMLAttributes<HTMLRfHotelElement>;
            "rf-navbar": LocalJSX.RfNavbar & JSXBase.HTMLAttributes<HTMLRfNavbarElement>;
            "rf-photo": LocalJSX.RfPhoto & JSXBase.HTMLAttributes<HTMLRfPhotoElement>;
            "rf-property": LocalJSX.RfProperty & JSXBase.HTMLAttributes<HTMLRfPropertyElement>;
            "rf-rooms": LocalJSX.RfRooms & JSXBase.HTMLAttributes<HTMLRfRoomsElement>;
        }
    }
}
